apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: streamforge
  name: streamforge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamforge-api
  template:
    metadata:
      labels:
        app: streamforge-api
    spec:
      containers:
        - name: api
          image: streamforge-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          workingDir: /app/services/api_gateway
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: PYTHONPATH
              value: /app
            - name: DATABASE_URL
              value: postgresql://admin:admin@postgres:5432/streamforge
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: MINIO_ENDPOINT
              value: minio:9000
