"""created video and video_rendition tables

Revision ID: 55dcb0ecb6ec
Revises: 0f11bbbb9aaa
Create Date: 2026-06-11 14:56:12.773624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dcb0ecb6ec'
down_revision: Union[str, Sequence[str], None] = '0f11bbbb9aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hls_master_url', sa.Text(), nullable=True))
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('videos', 'hls_master_url')
    # ### end Alembic commands ###
