apiVersion: apps/v1
kind: Deployment

metadata:
  name: streamforge-worker
  namespace: streamforge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: streamforge-worker

  template:
    metadata:
      labels:
        app: streamforge-worker

    spec:
      containers:
        - name: worker

          image: streamforge-worker:latest
          imagePullPolicy: Never

          env:
            - name: PYTHONPATH
              value: /app

            - name: RABBITMQ_HOST
              value: rabbitmq-service

            - name: MINIO_ENDPOINT
              value: minio-service:9000

            - name: DATABASE_URL
              value: postgresql://admin:admin@postgres-service:5432/streamforge

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.streamforge:4317

            - name: OTEL_SERVICE_NAME
              value: worker
